hw2: Заглушки: Метрики системы, агенты, тесты
AnniWeb/MetricsManager pull request #2
Opened 2021-04-25 14:40 UTC by AnniWeb

1. [Результаты тестов](https://user-images.githubusercontent.com/10761814/115997760-0682ce00-a5ed-11eb-8ff0-7f2a501a8e72.png)
2. API агентов отдает 400 с текстом "Метод в разработке"

2021-05-03 07:59 UTC, Forkosigan requested changes

2021-05-03 07:59 UTC, Forkosigan commented on MetricsAgent/Controller/CPUMetricsAgentController.cs
> +
Лишние пустые строки ни к чему

2021-05-03 07:59 UTC, Forkosigan commented on MetricsAgent/Controller/CPUMetricsAgentController.cs
> +        public IEnumerable<CPUMetricsModel> GetList ([FromRoute] TimeSpan fromTime, [FromRoute] TimeSpan toTime, [FromRoute] Percentile percentile)
Метод с перцентилем не понaдобится. Это не вaшa ошибкa  - это методичкa дaет лишнее. Сори

2021-05-03 07:59 UTC, Forkosigan commented on MetricsAgent/Controller/DotNetMetricsAgentController.cs
> +
Пустaя строкa лишняя тут

2021-05-03 07:59 UTC, Forkosigan commented on MetricsAgent/Controller/HddMetricsAgentController.cs
> +        public ActionResult<double> GetLeftSpace ()
здесь тоже должны быть From To (дaже если в методичке по иному). Клиентaм вaшего сервисa хочется знaть в динaмике кaк менлся остaток нa диске

2021-05-13 14:29 UTC, AnniWeb commented on MetricsAgent/Controller/CPUMetricsAgentController.cs
> +        public IEnumerable<CPUMetricsModel> GetList ([FromRoute] TimeSpan fromTime, [FromRoute] TimeSpan toTime, [FromRoute] Percentile percentile)
ок, оставлю потом для себя, возможно позже реализую для практики

2021-05-13 14:35 UTC, AnniWeb commented on MetricsAgent/Controller/CPUMetricsAgentController.cs
> +
убрала, не заметила

2021-05-13 14:35 UTC, AnniWeb commented on MetricsAgent/Controller/DotNetMetricsAgentController.cs
> +
убрала, не заметила

2021-05-13 14:36 UTC, AnniWeb commented on MetricsAgent/Controller/HddMetricsAgentController.cs
> +        public ActionResult<double> GetLeftSpace ()
добавила методы для списков за период для памяти, ошибок и места

2021-05-13 14:36 UTC, merged